#!/bin/sh
#
# rawhide - find files using pretty C expressions
# https://raf.org/rawhide
# https://github.com/raforg/rawhide
# https://codeberg.org/raforg/rawhide
#
# Copyright (C) 1990 Ken Stauffer, 2022-2023 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#
# 20231013 raf <raf@raf.org>

. tests/.common

label="-x/-X %s/%S prevent shell command injection"

touch $d/"cmdinjtest; cd tests >&- 2>&-; cd .$t >&- 2>&-; echo 'oops! command injection succeeded' > cmdinjtest.out"

label2="-x %s"
count_test
$rh -e f -x 'file %s' $d >/dev/null
rc=$?

if [ -f $d/cmdinjtest.out ]
then
	echo "TEST $t fail ($label - $label2)"
	echo $d/cmdinjtest.out:
	cat $d/cmdinjtest.out
	count_fail
	errors=1
elif [ $rc != 0 ]
then
	echo "TEST $t fail ($label - $label2)"
	count_fail
	errors=1
else
	[ x"$quiet" = x1 ] || echo "TEST $t pass ($label - $label2)"
fi

label2="-x %S"
count_test
$rh -e f -x "file $d/%S" $d >/dev/null
rc=$?

if [ -f $d/cmdinjtest.out ]
then
	echo "TEST $t fail ($label - $label2)"
	echo $d/cmdinjtest.out:
	cat $d/cmdinjtest.out
	count_fail
	errors=1
elif [ $rc != 0 ]
then
	echo "TEST $t fail ($label - $label2)"
	count_fail
	errors=1
else
	[ x"$quiet" = x1 ] || echo "TEST $t pass ($label - $label2)"
fi

label2="-X %s"
count_test
$rh -e f -X "cd $saved_pwd && file %s" $d >/dev/null
rc=$?

if [ -f $d/cmdinjtest.out ]
then
	echo "TEST $t fail ($label - $label2)"
	echo $d/cmdinjtest.out:
	cat $d/cmdinjtest.out
	count_fail
	errors=1
elif [ $rc != 0 ]
then
	echo "TEST $t fail ($label - $label2)"
	count_fail
	errors=1
else
	[ x"$quiet" = x1 ] || echo "TEST $t pass ($label - $label2)"
fi

label2="-X %S"
count_test
$rh -e f -X 'file %S' $d >/dev/null
rc=$?

if [ -f $d/cmdinjtest.out ]
then
	echo "TEST $t fail ($label - $label2)"
	echo $d/cmdinjtest.out:
	cat $d/cmdinjtest.out
	count_fail
	errors=1
elif [ $rc != 0 ]
then
	echo "TEST $t fail ($label - $label2)"
	count_fail
	errors=1
else
	[ x"$quiet" = x1 ] || echo "TEST $t pass ($label - $label2)"
fi

# Extra tricky

# These tests (by Stéphane Chazelas) show how `` is more dangerous
# than $() when interpolation of %s/%S is done by quoting with
# backslashes (which is the method that used to be used by rh).
# When a pathname contains backticks, those backticks were backslashed
# by rh, but those backslashes would be processed within any backticks
# in the shell command, and so the contents of the internal backticks
# would be executed by the shell when parsing the final resulting command.
#
# The first two (commented out) tests show the original behaviour with
# `` when interpolation was done by quoting. The next two show the new
# fixed behaviour where %s/%S are passed as positional arguments to sh -c
# as "$1"/"$2" thus eliminating the problem that it isn't actually possible
# to interpolate by quoting because the context in which the interpolation
# happens affects which method of quoting is needed, and it's impossible to
# know what context(s) will be used without actually parsing the shell
# command (which is not an option). The last two tests show the equivalent
# shell command using $() rather than `` which worked safely with both
# methods of interpolation.

mkdir $d/'`$X`'
touch $d/'`$X`'/f
#test_rawhide "X='echo tricky'             $rh -m1 -e 'd && !empty && \"[ -n \\\"\`$explicit_rh -ref -- %S\`\\\" ]\".sh' $d" ""             "rh: fstatat tricky: No such file or directory\n" 0 "backtick cmd with backticks in %S and arbitrary cmd with space in env (orig unsafe)"
#test_rawhide "X='/sbin/reboot-not-really' $rh -m1 -e 'd && !empty && \"[ -n \\\"\`$explicit_rh -ref -- %S\`\\\" ]\".sh' $d" "$d/\`\$X\`\n" "sh: 1: /sbin/reboot-not-really: not found\n" 0 "backtick cmd with backticks in %S and arbitrary cmd with slash in env (orig unsafe)"
test_rawhide "X='echo tricky'             $rh -m1 -e 'd && !empty && \"[ -n \\\"\`$explicit_rh -ref -- %S\`\\\" ]\".sh' $d" "$d/\`\$X\`\n" "" 0 "backtick cmd with backticks in %S and arbitrary cmd with space in env (safe)"
test_rawhide "X='/sbin/reboot-not-really' $rh -m1 -e 'd && !empty && \"[ -n \\\"\`$explicit_rh -ref -- %S\`\\\" ]\".sh' $d" "$d/\`\$X\`\n" "" 0 "backtick cmd with backticks in %S and arbitrary cmd with slash in env (safe)"
test_rawhide "X='echo tricky'             $rh -m1 -e 'd && !empty && \"[ -n \\\"\$($explicit_rh -ref -- %S)\\\" ]\".sh' $d" "$d/\`\$X\`\n" "" 0 "\$() cmd with backticks in %S and arbitrary cmd with space in env (safe)"
test_rawhide "X='/sbin/reboot-not-really' $rh -m1 -e 'd && !empty && \"[ -n \\\"\$($explicit_rh -ref -- %S)\\\" ]\".sh' $d" "$d/\`\$X\`\n" "" 0 "\$() cmd with backticks in %S and arbitrary cmd with slash in env (safe)"

# Test that defusing %s and %S does nothing when it starts with / or ./ or ../

mkdir $d/a

test_rawhide_pre_hook() { test_rh_cd_pre_hook; }
test_rawhide_post_hook() { test_rh_cd_post_hook; test_rh_sort_post_hook; }

test_rawhide "$explicit_rh -x 'echo %s %S' -M0 /"                                                "/ /\n"          "" 0 "defuse %s/%S for -x does nothing when starting with /"
test_rawhide "$explicit_rh -x 'echo %s %S' -M0 a"                                                "./a ./a\n"      "" 0 "defuse %s/%S for -x does something when not starting with / or ./ or ../"
test_rawhide "$explicit_rh -x 'echo %s %S' -M0 ./a"                                              "./a ./a\n"      "" 0 "defuse %s/%S for -x does nothing when starting with ./"
test_rawhide "$explicit_rh -x 'echo %s %S' -M0 ../.$t/a"                                         "../.$t/a ./a\n" "" 0 "defuse %s/%S for -x does nothing when starting with ../"
test_rawhide "$explicit_rh -X 'echo %s %S' -M0 /"                                                "/ /\n"          "" 0 "defuse %s/%S for -X does nothing when starting with /"
test_rawhide "$explicit_rh -X 'echo %s %S' -M0 a"                                                "./a ./a\n"      "" 0 "defuse %s/%S for -X does something when not starting with / or ./ or ../"
test_rawhide "$explicit_rh -X 'echo %s %S' -M0 ./a"                                              "./a ./a\n"      "" 0 "defuse %s/%S for -X does nothing when starting with /"
test_rawhide "$explicit_rh -X 'echo %s %S' -M0 ../.$t/a"                                         "../.$t/a ./a\n" "" 0 "defuse %s/%S for -X does something when not starting with / or ./ or ../"
test_rawhide "$explicit_rh -e '\"echo %s %S\".sh && 0' -M0 /"                                    "/ /\n"          "" 0 "defuse %s/%S for sh does nothing when starting with /"
test_rawhide "$explicit_rh -e '\"echo %s %S\".sh && 0' -M0 a"                                    "./a ./a\n"      "" 0 "defuse %s/%S for sh does something when not starting with / or ./ or ../"
test_rawhide "$explicit_rh -e '\"echo %s %S\".sh && 0' -M0 ./a"                                  "./a ./a\n"      "" 0 "defuse %s/%S for sh does nothing when starting with ./"
test_rawhide "$explicit_rh -e '\"echo %s %S\".sh && 0' -M0 ../.$t/a"                             "../.$t/a ./a\n" "" 0 "defuse %s/%S for sh does nothing when starting with ../"
test_rawhide "RAWHIDE_USER_SHELL=/bin/sh $explicit_rh -e '\"echo %s %S\".ush && 0' -M0 /"        "/ /\n"          "" 0 "defuse %s/%S for ush does nothing when starting with /"
test_rawhide "RAWHIDE_USER_SHELL=/bin/sh $explicit_rh -e '\"echo %s %S\".ush && 0' -M0 a"        "./a ./a\n"      "" 0 "defuse %s/%S for ush does something when not starting with / or ./ or ../"
test_rawhide "RAWHIDE_USER_SHELL=/bin/sh $explicit_rh -e '\"echo %s %S\".ush && 0' -M0 ./a"      "./a ./a\n"      "" 0 "defuse %s/%S for ush does nothing when starting with ./"
test_rawhide "RAWHIDE_USER_SHELL=/bin/sh $explicit_rh -e '\"echo %s %S\".ush && 0' -M0 ../.$t/a" "../.$t/a ./a\n" "" 0 "defuse %s/%S for ush does nothing when starting with ../"

test_rawhide_pre_hook() { true; }
test_rawhide_post_hook() { true; }

finish

exit $errors

# vi:set ts=4 sw=4:
