#!/bin/sh
#
# rawhide - find files using pretty C expressions
# https://raf.org/rawhide
# https://github.com/raforg/rawhide
# https://codeberg.org/raforg/rawhide
#
# Copyright (C) 1990 Ken Stauffer, 2022-2023 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#
# 20231013 raf <raf@raf.org>

. tests/.common

label="-x/-X/sh/ush cmd buf size handling"
label2="-x"

touch $d/"abcd "

test_cmdbufsize()
{
	max="$1"
	cmd="$2"
	expected_stdout="$3"
	expected_stderr="$4"
	expected_rc="$5"
	desc="$6"

	test_rawhide "RAWHIDE_TEST_CMD_MAX=$max $cmd" "$expected_stdout" "$expected_stderr" "$expected_rc" "$label2 - $desc"
}

# Where buf size checks are:
# - not interpolating (char is not %)
# - interpolating %s
# - interpolating %S
# - interpolating %%

# These require a buffer size of at least 19
# echo 6789012345678
test_cmdbufsize 20 "$rh -x 'echo 6789012345678' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: small"
test_cmdbufsize 19 "$rh -x 'echo 6789012345678' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: max"
test_cmdbufsize 18 "$rh -x 'echo 6789012345678' $d" ""                              "./rh: command is too big: echo 6789012345678 (tests/.$t)\n./rh: command is too big: echo 6789012345678 (tests/.$t/abcd )\n" 1 "not interpolating: too big"

# These require a buffer size of at least 10
# echo "$1"
test_cmdbufsize 11 "$rh -x 'echo %s' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: small"
test_cmdbufsize 10 "$rh -x 'echo %s' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: max"
test_cmdbufsize  9 "$rh -x 'echo %s' $d" ""                                 "./rh: command is too big: echo %%s (tests/.$t)\n./rh: command is too big: echo %%s (tests/.$t/abcd )\n" 1 "interpolating %s: too big"

# These require a buffer size of at least 10
# echo "$2"
test_cmdbufsize 11 "$rh -x 'echo %S' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: small"
test_cmdbufsize 10 "$rh -x 'echo %S' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: max"
test_cmdbufsize 09 "$rh -x 'echo %S' $d" ""                 "./rh: command is too big: echo %%S (tests/.$t)\n./rh: command is too big: echo %%S (tests/.$t/abcd )\n" 1 "interpolating %S: too big"

# These require a buffer size of at least 12
# echo "$1" %
test_cmdbufsize 13 "$rh -x 'echo %s %%' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: small"
test_cmdbufsize 12 "$rh -x 'echo %s %%' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: max"
test_cmdbufsize 11 "$rh -x 'echo %s %%' $d" ""                                       "./rh: command is too big: echo %%s %%%% (tests/.$t)\n./rh: command is too big: echo %%s %%%% (tests/.$t/abcd )\n" 1 "interpolating %%: too big"

label2="-X"

# These require a buffer size of at least 19
# echo 6789012345678
test_cmdbufsize 20 "$rh -X 'echo 6789012345678' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: small"
test_cmdbufsize 19 "$rh -X 'echo 6789012345678' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: max"
test_cmdbufsize 18 "$rh -X 'echo 6789012345678' $d" ""                              "./rh: command is too big: echo 6789012345678 (tests/.$t)\n./rh: command is too big: echo 6789012345678 (tests/.$t/abcd )\n" 1 "not interpolating: too big"

# These require a buffer size of at least 10
# echo "$1"
test_cmdbufsize 11 "$rh -X 'echo %s' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: small"
test_cmdbufsize 10 "$rh -X 'echo %s' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: max"
test_cmdbufsize  9 "$rh -X 'echo %s' $d" ""                                 "./rh: command is too big: echo %%s (tests/.$t)\n./rh: command is too big: echo %%s (tests/.$t/abcd )\n" 1 "interpolating %s: too big"

# These require a buffer size of at least 10
# echo "$2"
test_cmdbufsize 11 "$rh -X 'echo %S' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: small"
test_cmdbufsize 10 "$rh -X 'echo %S' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: max"
test_cmdbufsize 09 "$rh -X 'echo %S' $d" ""                 "./rh: command is too big: echo %%S (tests/.$t)\n./rh: command is too big: echo %%S (tests/.$t/abcd )\n" 1 "interpolating %S: too big"

# These require a buffer size of at least 12
# echo "$1" %
test_cmdbufsize 13 "$rh -X 'echo %s %%' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: small"
test_cmdbufsize 12 "$rh -X 'echo %s %%' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: max"
test_cmdbufsize 11 "$rh -X 'echo %s %%' $d" ""                                       "./rh: command is too big: echo %%s %%%% (tests/.$t)\n./rh: command is too big: echo %%s %%%% (tests/.$t/abcd )\n" 1 "interpolating %%: too big"

label2=".sh"

# These require a buffer size of at least 19
# echo 6789012345678
test_cmdbufsize 20 "$rh -e '\"echo 6789012345678\".sh && 0' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: small"
test_cmdbufsize 19 "$rh -e '\"echo 6789012345678\".sh && 0' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: max"
test_cmdbufsize 18 "$rh -e '\"echo 6789012345678\".sh && 0' $d" ""                              "./rh: command is too big: echo 6789012345678 (tests/.$t)\n./rh: command is too big: echo 6789012345678 (tests/.$t/abcd )\n" 1 "not interpolating: too big"

# These require a buffer size of at least 10
# echo "$1"
test_cmdbufsize 11 "$rh -e '\"echo %s\".sh && 0' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: small"
test_cmdbufsize 10 "$rh -e '\"echo %s\".sh && 0' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: max"
test_cmdbufsize  9 "$rh -e '\"echo %s\".sh && 0' $d" ""                                 "./rh: command is too big: echo %%s (tests/.$t)\n./rh: command is too big: echo %%s (tests/.$t/abcd )\n" 1 "interpolating %s: too big"

# These require a buffer size of at least 10
# echo "$2"
test_cmdbufsize 11 "$rh -e '\"echo %S\".sh && 0' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: small"
test_cmdbufsize 10 "$rh -e '\"echo %S\".sh && 0' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: max"
test_cmdbufsize  9 "$rh -e '\"echo %S\".sh && 0' $d" ""                 "./rh: command is too big: echo %%S (tests/.$t)\n./rh: command is too big: echo %%S (tests/.$t/abcd )\n" 1 "interpolating %S: too big"

# These require a buffer size of at least 12
# echo "$1: %
test_cmdbufsize 13 "$rh -e '\"echo %s %%\".sh && 0' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: small"
test_cmdbufsize 12 "$rh -e '\"echo %s %%\".sh && 0' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: max"
test_cmdbufsize 11 "$rh -e '\"echo %s %%\".sh && 0' $d" ""                                       "./rh: command is too big: echo %%s %%%% (tests/.$t)\n./rh: command is too big: echo %%s %%%% (tests/.$t/abcd )\n" 1 "interpolating %%: too big"

label2=".ush"

if [ $(id -u) != 0 ]
then
	# These require a buffer size of at least 19
	# echo 6789012345678
	test_cmdbufsize 20 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo 6789012345678\".ush && 0' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: small"
	test_cmdbufsize 19 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo 6789012345678\".ush && 0' $d" "6789012345678\n6789012345678\n" ""                                                                                                                          0 "not interpolating: max"
	test_cmdbufsize 18 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo 6789012345678\".ush && 0' $d" ""                              "./rh: command is too big: echo 6789012345678 (tests/.$t)\n./rh: command is too big: echo 6789012345678 (tests/.$t/abcd )\n" 1 "not interpolating: too big"

	# These require a buffer size of at least 14
	# echo $argv[1]
	test_cmdbufsize 11 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %s\".ush && 0' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: small"
	test_cmdbufsize 10 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %s\".ush && 0' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: max"
	test_cmdbufsize  9 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %s\".ush && 0' $d" ""                                 "./rh: command is too big: echo %%s (tests/.$t)\n./rh: command is too big: echo %%s (tests/.$t/abcd )\n" 1 "interpolating %s: too big"

	# These require a buffer size of at least 14
	# echo $argv[2]
	test_cmdbufsize 11 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %S\".ush && 0' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: small"
	test_cmdbufsize 10 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %S\".ush && 0' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: max"
	test_cmdbufsize  9 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %S\".ush && 0' $d" ""                 "./rh: command is too big: echo %%S (tests/.$t)\n./rh: command is too big: echo %%S (tests/.$t/abcd )\n" 1 "interpolating %S: too big"

	# These require a buffer size of at least 16
	# echo $argv[1] %
	test_cmdbufsize 13 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %s %%\".ush && 0' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: small"
	test_cmdbufsize 12 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %s %%\".ush && 0' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: max"
	test_cmdbufsize 11 "RAWHIDE_USER_SHELL=/bin/sh $rh -e '\"echo %s %%\".ush && 0' $d" ""                                       "./rh: command is too big: echo %%s %%%% (tests/.$t)\n./rh: command is too big: echo %%s %%%% (tests/.$t/abcd )\n" 1 "interpolating %%: too big"

	label2=".ush (fish)"

	if [ -x /usr/bin/fish ]
	then
		# These require a buffer size of at least 19
		# echo 6789012345678
		test_cmdbufsize 20 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo 6789012345678\".ush' $d" "6789012345678\n6789012345678\n$d\n$d/abcd \n" ""                                                                                                                          0 "not interpolating: small"
		test_cmdbufsize 19 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo 6789012345678\".ush' $d" "6789012345678\n6789012345678\n$d\n$d/abcd \n" ""                                                                                                                          0 "not interpolating: max"
		test_cmdbufsize 18 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo 6789012345678\".ush' $d" ""                                       "./rh: command is too big: echo 6789012345678 (tests/.$t)\n./rh: command is too big: echo 6789012345678 (tests/.$t/abcd )\n" 1 "not interpolating: too big"

		# These require a buffer size of at least 14
		# echo $argv[1]
		test_cmdbufsize 15 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %s\".ush && 0' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: small"
		test_cmdbufsize 14 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %s\".ush && 0' $d" "./tests/.$t\n./tests/.$t/abcd \n" ""                                                                                                       0 "interpolating %s: max"
		test_cmdbufsize 13 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %s\".ush && 0' $d" ""                                 "./rh: command is too big: echo %%s (tests/.$t)\n./rh: command is too big: echo %%s (tests/.$t/abcd )\n" 1 "interpolating %s: too big"

		# These require a buffer size of at least 14
		# echo $argv[2]
		test_cmdbufsize 15 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %S\".ush && 0' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: small"
		test_cmdbufsize 14 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %S\".ush && 0' $d" "./.$t\n./abcd \n" ""                                                                                                       0 "interpolating %S: max"
		test_cmdbufsize 13 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %S\".ush && 0' $d" ""                 "./rh: command is too big: echo %%S (tests/.$t)\n./rh: command is too big: echo %%S (tests/.$t/abcd )\n" 1 "interpolating %S: too big"

		# These require a buffer size of at least 16
		# echo $argv[1] %
		test_cmdbufsize 17 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %s %%\".ush && 0' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: small"
		test_cmdbufsize 16 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %s %%\".ush && 0' $d" "./tests/.$t %%\n./tests/.$t/abcd  %%\n" ""                                                                                                                 0 "interpolating %%: max"
		test_cmdbufsize 15 "RAWHIDE_USER_SHELL=/usr/bin/fish $rh -e '\"echo %s %%\".ush && 0' $d" ""                                       "./rh: command is too big: echo %%s %%%% (tests/.$t)\n./rh: command is too big: echo %%s %%%% (tests/.$t/abcd )\n" 1 "interpolating %%: too big"
	fi
fi

finish

exit $errors

# vi:set ts=4 sw=4:
