#!/bin/sh
#
# rawhide - find files using pretty C expressions
# https://raf.org/rawhide
# https://github.com/raforg/rawhide
# https://codeberg.org/raforg/rawhide
#
# Copyright (C) 1990 Ken Stauffer, 2022-2023 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#
# 20231013 raf <raf@raf.org>

. tests/.common

label="trivial options (-h --help -V --version invalid)"

touch $d/abc

test_rawhide_post_hook() { test_rh_first_line_post_hook; }

test_rawhide      "./rh -h"        "usage: rh [options] [--] [path...]\n" "" 0 "-h option"
test_rawhide      "./rh --help"    "usage: rh [options] [--] [path...]\n" "" 0 "--help option"
test_rawhide_grep "./rh -V"        "^rh-[0-9.]+[a-z]?$"                   "" 0 "-V option"
test_rawhide_grep "./rh --version" "^rh-[0-9.]+[a-z]?$"                   "" 0 "--version option"

test_rawhide "./rh -!" "" "./rh: invalid option: -! (see ./rh -h for help)\n" 1 "invalid option"

finish

exit $errors

# vi:set ts=4 sw=4:
